select * from `customer_shopping_behavior (1)`;
-- Q1. What is the total revenue generated by male vs female customers ?
select gender, sum(purchase_amount) as total_revenue from `customer_shopping_behavior (1)`
group by gender;
    
-- Q2. Which customers used a discount but still spent more than the average purchase amount ?
select customer_id, purchase_amount from `customer_shopping_behavior (1)`
where discount_applied = "yes" and purchase_amount >= (select avg(purchase_amount) from `customer_shopping_behavior (1)`);

-- Q3. Which are the top 5 products with highest average review rating ?
select item_purchased, round(avg(review_rating),2) as product_review_rating
from `customer_shopping_behavior (1)`
group by item_purchased
order by product_review_rating desc limit 5;

-- Q4. Compare the average purchase amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount),2) as average_purchase_amount
from `customer_shopping_behavior (1)`
where shipping_type in ("Standard","Express")
group by shipping_type;

-- Q5. Do subscribed customers spend more ? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as average_spend,
sum(purchase_amount) as total_revenue
from `customer_shopping_behavior (1)`
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied ?
select item_purchased,
round(100*(sum(case when discount_applied = "yes" then 1 else 0 end)/count(*)),2) as discount_rate
from `customer_shopping_behavior (1)`
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning and Loyal based on their
-- total number of previous purchases, and show the count of each segment.
with customer as (
select customer_id, case when previous_purchases = 1 then "New"
when previous_purchases between 2 and 10 then "Returning"
else "Loyal" end as category
from `customer_shopping_behavior (1)`)
select category, count(customer_id) as customer_count
from customer
group by category;

-- Q8. What are the top 3 most purchased products within each category ?
with ranked as (select category, item_purchased, count(purchase_amount) as purchase_count,
row_number()over(partition by category order by count(purchase_amount) desc) as rn
from `customer_shopping_behavior (1)`
group by category, item_purchased)
select category, item_purchased,purchase_count, rn
from ranked where rn <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
select subscription_status, count(customer_id) as customer_count
from `customer_shopping_behavior (1)`
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group ?
select age_group, sum(purchase_amount) as total_revenue
from `customer_shopping_behavior (1)`
group by age_group
order by total_revenue desc;